#!/bin/bash
echo "=== $(date) ===" >> /mnt/rdisk/hoangvuong/rclone.log
rclone copy --update --verbose --transfers 30 --checkers 8 --contimeout 60s --timeout 600s --retries 3 --low-level-retries 10 --stats 1s --stats-file-name-length 0 "/mnt/rdisk/hoangvuong/Rclone_HPC" "GoogleDrive:Rclone_HPC"
